# Generated by Django 3.0.5 on 2020-04-14 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_role', models.CharField(max_length=64)),
                ('call_order', models.IntegerField()),
            ],
            options={
                'ordering': ['call_order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.ManyToManyField(through='dauplerapi.Assignment', to='dauplerapi.Person')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dauplerapi.Person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dauplerapi.Team'),
        ),
    ]
